## CSV

In [2]:
import numpy as np

In [28]:
# ruta del archivo, delimiter= ',' es el separador, 
# name=True significa que hay una fila que funciona como columnas
np.genfromtxt('example.csv', delimiter=',', names=True, dtype=None)

array([(12341324, 25, 1), (34565678, 23, 1), (32453245, 30, 0)],
      dtype=[('id', '<i8'), ('age', '<i8'), ('isVaccinated', '<i8')])

In [29]:
data_set = np.genfromtxt('example.csv', delimiter=',', names=True, dtype=None)

data_set['id']

array([12341324, 34565678, 32453245])

In [10]:
data_set['age']

array([25., 23., 30.])

Hallar la edad promedio

Hallar cuantos vacunados hay en el data_set

In [15]:
# Hallamos la edad promedio

edades = data_set['age']

print(edades)

promedio = edades.mean()

print(promedio)

[25. 23. 30.]
26.0


In [24]:
# Hallar la cantidad de vacunados

# 1 -> estar vacunado
# 0 -> no vacunado

data_vacunados = data_set['isVaccinated']  == 1

print(data_vacunados)

np.count_nonzero(data_vacunados)


[ True  True False]


2

In [19]:
np.count_nonzero(data_set['isVaccinated'])

2

In [3]:
health_covid = np.genfromtxt(
  'COVID-19_Reported_Patient_Impact_and_Hospital_Capacity_by_State_Timeseries.csv',
  delimiter=',',
  names=True,
  dtype= np.object_,
  max_rows=3
)

health_covid['date']

array([b'2021/01/03', b'2020/12/28', b'2020/10/16'], dtype=object)