In [1]:
import numpy as np

In [2]:
np.array([[1, 0, 0],[0, 1, 0],[0, 0, 1]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Arrays Intrinsecos

In [9]:
np.zeros((4, 4), np.uint8)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [10]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros((4, 5, 6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(4, 11, 3)

array([ 4,  7, 10])

### RESHAPE

In [20]:
ndArray = np.array([2, 3, 4, 5, 6, 7])

ndArray.reshape(2, 3)

array([[2, 3, 4],
       [5, 6, 7]])

In [23]:
np.arange(7, 24, 3).reshape(3, 2)

array([[ 7, 10],
       [13, 16],
       [19, 22]])

In [29]:
stream_datos  = np.arange(0, 101, 5)

print(stream_datos)

columns = 7

stream_datos.reshape(stream_datos.size//columns, columns)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


array([[  0,   5,  10,  15,  20,  25,  30],
       [ 35,  40,  45,  50,  55,  60,  65],
       [ 70,  75,  80,  85,  90,  95, 100]])

In [30]:
np.linspace(0, 21, 8)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [31]:
np.random.random((4,5))

array([[0.84143667, 0.52471366, 0.85887131, 0.32407344, 0.57940786],
       [0.27373962, 0.21474823, 0.42609031, 0.80118233, 0.96664824],
       [0.65350434, 0.1384324 , 0.6081113 , 0.39761993, 0.75234774],
       [0.07938079, 0.9686709 , 0.7567494 , 0.69083389, 0.75916068]])

## Producto de matrices

In [33]:
arrayA = np.array([
  [4,5,6],
  [1,2,1]
])

arrayB = np.array([
  [1, 1],
  [1, 2],
  [5, 9]
])

arrayA.dot(arrayB)



array([[39, 68],
       [ 8, 14]])

## Funciones universales

In [40]:
import math

from numpy import mat
array_mock = np.array([math.pi, math.pi/4, math.pi/3, 5*math.pi/12], np.float32)

np.tan(array_mock)

array([8.7422777e-08, 1.0000000e+00, 1.7320509e+00, 3.7320504e+00],
      dtype=float32)

## Funciones de agregacion

In [45]:
mock_array = np.arange(1,11)
print(mock_array)

mock_array.sum()

mock_array.min()

mock_array.mean()

mock_array.std()


[ 1  2  3  4  5  6  7  8  9 10]


2.8722813232690143