# NDARRAY

ndArray -> Una coleccion de elementos del mismo tipo ordenados y no son extensibles

importamos numpy

In [2]:
import numpy as np

Creando un ndArray, este es un objeto que le pertence a numpy

In [3]:
arrayA = np.array([1, 2, 3, 4, 5, 6])

print(arrayA)
print('El tipo de array es ', type(arrayA))

[1 2 3 4 5 6]
El tipo de array es  <class 'numpy.ndarray'>


Otra forma de crear ndArrays es con tuplas

In [4]:
arrayB = np.array((1, 2, 3, 4, 5, 6))

print(arrayB)

[1 2 3 4 5 6]


Todos los elementos de un ndarray tienen que ser del mismo tipo

In [4]:
np.array([1, 2, 3, "4", 1.5], np.int32)

array([1, 2, 3, 4, 1], dtype=int32)

In [18]:
array_1dimension = np.array([1,2,3,4,5])
print('array 1 dimension')
print('total de elementos',array_1dimension.size)
print(array_1dimension.shape)
print(array_1dimension.dtype)
print(array_1dimension.ndim)

array 1 dimension
total de elementos 5
(5,)
int64
1


In [20]:
array_2dimension = np.array([
  [2, 3, 4],
  [4, 5, 9]
])
print('array 2 dimensiones')
print('total de elementos',array_2dimension.size)
print('fila columna', array_2dimension.shape)
print(array_2dimension.dtype)
print(array_2dimension.ndim)

array 2 dimensiones
total de elementos 6
fila columna (2, 3)
int64
2


In [22]:
array_3dimension = np.array([
  [[2, 3], [3, 5], [4, 6]],
  [[4, 4], [5, 9], [9, 11]]
])
print('array 3 dimensiones')
print('total de elementos',array_3dimension.size)
print(array_3dimension.shape)
print(array_3dimension.dtype)
print(array_3dimension.ndim)

array 3 dimensiones
total de elementos 12
(2, 3, 2)
int64
3
