# Operaciones con escalares
---

## Acceso y mutabilidad

In [2]:
import numpy as np

In [7]:
vector1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# accediendo a un elemento por su indice
print(vector1[3])

# accediendo por su posicion de izqquierda a derecha
print(vector1[-1])

# slicing
print(vector1[1:3])

# slicing con step
print(vector1[0::2])

4
8
[2 3]
[1 3 5 7]


In [10]:
matriz = np.array([
  [1,2,3,4,5],
  [5,6,7,8,9]
])

print(matriz[1])
print(matriz[0, 0])
print(matriz[0, 3])

[5 6 7 8 9]
1
4


In [16]:
array_3dimension = np.array([
  [[1,2,3], [4,5,6]],
  [[1,4,7], [9,1,5]]
])

print(array_3dimension[0, 1, 2])

6


In [19]:
arrayA = np.array([1,2,3,4,5])

# arrayB es otro identificador de arrayA y por lo tanto apunta al mismo objeto
arrayB = arrayA

arrayA[2] = 20
print(arrayA)
print(arrayB)

[ 1  2 20  4  5]
[ 1  2 20  4  5]


In [20]:
arrayB[-1] = 30

print(arrayB)
print(arrayA)

[ 1  2 20  4 30]
[ 1  2 20  4 30]


# Operaciones

Adicion

In [22]:
print(vector1)
print(vector1+4)
print(vector1)

[1 2 3 4 5 6 7 8]
[ 5  6  7  8  9 10 11 12]
[1 2 3 4 5 6 7 8]


Multiplicacion

In [23]:
print(vector1)
print(3*vector1)

[1 2 3 4 5 6 7 8]
[ 3  6  9 12 15 18 21 24]


In [24]:
array_to_copy = np.array([2,3,4,5,6,7])
copied_array = 1*array_to_copy

array_to_copy[-1] = 50

print(array_to_copy)
print(copied_array)

[ 2  3  4  5  6 50]
[2 3 4 5 6 7]


In [25]:
array_to_copy_2 = np.array([2,3,4,5,6,7])
copied_array_2 = array_to_copy.copy()

array_to_copy[-1] = 50

print(array_to_copy_2)
print(copied_array_2)


[2 3 4 5 6 7]
[ 2  3  4  5  6 50]
